-- ══════════════════════════════════════════════════════════════════════════════
-- Mart: mart_sales_by_region
-- Aggregates daily sales metrics by region for executive dashboards
-- ══════════════════════════════════════════════════════════════════════════════

{{
    config(
        materialized='table',
        tags=['mart', 'daily'],
        post_hook="COMMENT ON TABLE {{ this }} IS 'Daily sales aggregation by region — generated by dbt in Project B Governance Stack'"
    )
}}

with daily_sales as (
    select
        transaction_date,
        region,
        region_name,
        product_category,
        store_type,

        -- ── Aggregated Measures ──────────────────────────────────────────────
        count(*)                            as total_transactions,
        sum(quantity)                       as total_units_sold,
        sum(total_amount)                   as total_revenue,
        avg(total_amount)                   as avg_transaction_value,
        min(total_amount)                   as min_transaction_value,
        max(total_amount)                   as max_transaction_value,

        -- ── Transaction Mix ──────────────────────────────────────────────────
        count(case when transaction_tier = 'high_value' then 1 end)   as high_value_transactions,
        count(case when transaction_tier = 'medium_value' then 1 end) as medium_value_transactions,
        count(case when transaction_tier = 'low_value' then 1 end)    as low_value_transactions

    from {{ ref('stg_pos_transactions') }}
    group by
        transaction_date,
        region,
        region_name,
        product_category,
        store_type
)

select
    *,
    -- ── Percentage Calculations ──────────────────────────────────────────
    round(
        high_value_transactions::numeric / nullif(total_transactions, 0) * 100, 2
    ) as high_value_pct,

    -- ── Revenue per Unit ─────────────────────────────────────────────────
    round(
        total_revenue::numeric / nullif(total_units_sold, 0), 2
    ) as revenue_per_unit

from daily_sales
