-- ══════════════════════════════════════════════════════════════════════════════
-- Mart: mart_product_performance
-- Product-level performance metrics for category management
-- ══════════════════════════════════════════════════════════════════════════════

{{
    config(
        materialized='table',
        tags=['mart', 'daily'],
        post_hook="COMMENT ON TABLE {{ this }} IS 'Product performance metrics — generated by dbt in Project B Governance Stack'"
    )
}}

with product_metrics as (
    select
        transaction_date,
        product_id,
        product_name,
        product_category,

        -- ── Volume Metrics ───────────────────────────────────────────────────
        count(*)                            as total_transactions,
        sum(quantity)                       as total_units_sold,
        sum(total_amount)                   as total_revenue,
        avg(unit_price)                     as avg_unit_price,

        -- ── Distribution Metrics ─────────────────────────────────────────────
        count(distinct region)              as regions_sold_in,
        count(distinct store_type)          as store_types_sold_in,
        count(distinct pos_id)              as unique_pos_terminals

    from {{ ref('stg_pos_transactions') }}
    group by
        transaction_date,
        product_id,
        product_name,
        product_category
),

ranked as (
    select
        *,
        -- ── Ranking ──────────────────────────────────────────────────────────
        row_number() over (
            partition by transaction_date, product_category
            order by total_revenue desc
        ) as category_revenue_rank,

        -- ── Revenue Share ────────────────────────────────────────────────────
        round(
            total_revenue::numeric / nullif(
                sum(total_revenue) over (partition by transaction_date), 0
            ) * 100, 2
        ) as daily_revenue_share_pct

    from product_metrics
)

select * from ranked
